before:
  hooks:
    - go generate -x
    - go mod tidy -v

builds:
  - id: "agent"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ldflags:
      - -s -w
      - -X github.com/metatron-code/metatron-agent/internal/vars.Version={{.Version}}
      - -X github.com/metatron-code/metatron-agent/internal/vars.Commit={{.Commit}}
      - -X github.com/metatron-code/metatron-agent/internal/vars.DefaultEncryptPassword={{ .Env.DEFAULT_ENCRYPTION_KEY }}

release:
  skip_upload: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'

checksum:
  disable: true

snapcrafts:
  - builds:
      - agent
    name: metatron
    summary: Global Monitoring Agent
    description: |
      Monitoring agent for distributed checks.
      Designed to research the structure of the Internet.
    channel_templates:
      - stable
    grade: stable
    confinement: strict
    publish: true
    apps:
      agent:
        daemon: simple
        command: metatron-agent
        restart_condition: "always"
        plugs:
          - network
          - network-bind
