name: tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'
          skip-cache: true

      - name: Go Tests
        run: go test -v ./...
